FROM mondoshivan/rbenv:2.2.9

ENV APP_HOME /var/issue_tracker
ENV HOME /root

RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

COPY assets $APP_HOME/assets
COPY lib $APP_HOME/lib
COPY public $APP_HOME/public
COPY spec $APP_HOME/spec
COPY views $APP_HOME/views
COPY Gemfile $APP_HOME/Gemfile
COPY config.ru $APP_HOME/config.ru

RUN chmod -R 755 /var/issue_tracker

RUN bash -l -c "bundle install --with test"

CMD /bin/bash -i -c "rspec ${APP_HOME}/spec/spec_helper.rb"